name: Veracode Static Analysis Pipeline Scan + Agent SCA

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, '*' ]
  schedule:
    - cron: '17 5 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: verademo.war
        path: target/verademo.war

  Veracode_Pipeline_Scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - run: unzip -o pipeline-scan-LATEST.zip

    - uses: actions/download-artifact@v2
      with:
        name: verademo.war
        path: /tmp

    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: java -jar pipeline-scan.jar --veracode_api_id '${{secrets.VERACODE_API_ID}}' --veracode_api_key '${{secrets.VERACODE_API_KEY}}' --fail_on_severity="Very High, High" --file /tmp/verademo.war
      continue-on-error: True

    - uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: ScanResults
        path: results.json

  Veracode_Agent_Based_SCA:
    runs-on: ubuntu-latest
    env: 
      SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
    steps:
    - name: Veracode Dependency Scanning
      uses: veracode/veracode-sca@v1.09
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        update_advisor: TRUE
        url: https://github.com/deschenesdemo2/VD_Auto_PR_SCA
        fail-on-cvss: 5
        path: .
        debug: FALSE

  Convert_output:
    needs: Veracode_Pipeline_Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: ScanResults
        path: /tmp
        
    - name: Convert pipeline scan output to SARIF format
      id: convert
      uses: veracode/veracode-pipeline-scan-results-to-sarif@master
      with:
        pipeline-results-json: /tmp/results.json
        
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: veracode-results.sarif
