# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json, and convert to SARIF for upload as a code scanning alert

name: Veracode Static Analysis Pipeline Scan + Agent SCA

on:
  workflow_dispatch:
  pull_request:
    branches: [master, '*']
  schedule:
    - cron: '17 5 * * 2'

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: verademo.war
          path: target/verademo.war

  # Veracode Static Analysis Pipeline Scan job
  Veracode_Pipeline_Scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download pipeline scan jar
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip

      - name: Unzip pipeline scan package
        run: unzip -o pipeline-scan-LATEST.zip

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: verademo.war
          path: /tmp

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Run Veracode Pipeline Scan
        run: java -jar pipeline-scan.jar \
          --veracode_api_id '${{ secrets.VERACODE_API_ID }}' \
          --veracode_api_key '${{ secrets.VERACODE_API_KEY }}' \
          --fail_on_severity="Very High, High" \
          --file /tmp/verademo.war
        continue-on-error: true

      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: ScanResults
          path: results.json

  # Veracode Agent-Based SCA job
  Veracode_Agent_Based_SCA:
    runs-on: ubuntu-latest
    env:
      SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
    steps:
      - name: Veracode Dependency Scanning
        uses: veracode/veracode-sca@v1.09
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          update_advisor: true
          url: https://github.com/deschenesdemo2/VD_Auto_PR_SCA
          fail-on-cvss: 5
          path: .
          debug: false

  # Convert pipeline scan output to SARIF format and upload as a Code Scanning alert
  Convert_output:
    needs: Veracode_Pipeline_Scan
    runs-on: ubuntu-latest
    steps:
      - name: Download scan results artifact
        uses: actions/download-artifact@v3
        with:
          name: ScanResults
          path: /tmp

      - name: Convert pipeline scan output to SARIF format
        id: convert
        uses: veracode/veracode-pipeline-scan-results-to-sarif@master
        with:
          pipeline-results-json: /tmp/results.json

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: veracode-results.sarif
